### ISSUE TITLE
class names

### ISSUE THREAD

**Issue by cjessett** [tina-pina/ColmarAcademy#2]
(Important) [Here](https://github.com/tina-pina/ColmarAcademy/blob/0ce15ad9bfd8a785a98f62d058a96c662d2455a0/index.html#L174) you should use a dash instead of an underscore in your css class name. Since you use a dash in all other class names you should be consistent and do that here. It's also conventional to use a dash.

**Comment by tina-pina** [comment]
i changed this one!thanks a lot!
